base_model: NousResearch/Llama-2-7b-hf
base_model_config: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true
hub_model_id: refine-gen-cfg-sum-llama2-axolotl

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: ./Code_Refinement/train-cfg-sum.jsonl
    ds_type: json
    type: alpaca
dataset_prepared_path:
output_dir: ./llama2-refine-gen-cfg-sum-qlora-out

test_datasets:
  - path: ./Code_Refinement/val-cfg-sum.jsonl
    ds_type: json
    type: alpaca
    split: train # important 

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: axolotl-llama2-7b-ref-gen-cfg-sum
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

# true hyperparameters
lora_on_cpu: true
gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: 
tf32: false # important

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 10
xformers_attention:
flash_attention: false # important

deepspeed: deepspeed_configs/zero1.json

warmup_steps: 100
# evals_per_epoch: 4
# saves_per_epoch: 1
eval_steps: 0.2
save_strategy: epoch
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
